canonical:          http://julienmoumne.github.io
redirect_to: http://www.github.com
name :              &name Julien Moumné
profession :        &profession Software Engineer, Paris, France

title:              *name
tagline:            *profession

permalink:           pretty

collections:
  reading-notes:
    output: true

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      type: "posts"
  - scope:
      type: "reading-notes"
    values:
      layout: "reading-notes"
      type: "reading-notes"
