canonical:          http://moumne.com
name :              &name Julien Moumné
profession :        &profession Software Craftsman, Paris, France

title:              *name
tagline:            *profession

permalink:           pretty

collections:
  reading-notes:
    output: true

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      type: "posts"
  - scope:
      type: "reading-notes"
    values:
      layout: "reading-notes"
      type: "reading-notes"